# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: sx-cnp-oss-jokl-app-prod.demo.kubrix.cloud
    dns.gardener.cloud/ttl: "180"
  hosts:
    - host: sx-cnp-oss-jokl-app-prod.demo.kubrix.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
